// Code generated by "stringer -type=ItemKind"; DO NOT EDIT.

package core

import "strconv"

const _ItemKind_name = "StringListDict"

var _ItemKind_index = [...]uint8{0, 6, 10, 14}

func (i ItemKind) String() string {
	if i < 0 || i >= ItemKind(len(_ItemKind_index)-1) {
		return "ItemKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ItemKind_name[_ItemKind_index[i]:_ItemKind_index[i+1]]
}
